version: "3.8"

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/app.py
      - OLLAMA_HOST=http://host.docker.internal:11434  # Conecta al modelo en tu máquina local
    command: flask run --host=0.0.0.0