services:
  
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000" # Puerto expuesto para la API Flask
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    networks:
      - ollama-network

    
    restart: always

  ollama:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ollama
    pull_policy: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    #deploy:
    #  resources:
    #    reservations:
    #      cpus: '4'
    #      memory: 8G
    command: serve
    networks:
      - ollama-network

    restart: always

networks:
  ollama-network:
    driver: bridge


volumes:
  ollama_data: # Volumen compartido entre sesiones de Docker
