services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/app.py
      - OLLAMA_MODEL_PATH=/root/.ollama
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    command: -d -v ollama:/root/.ollama -p 11434:11434 --name ollama
    volumes:
      - ollama:/root/.ollama
    expose:
      - "11434"

volumes:
  ollama: